/* ============================================================
   Segregation Check — DATA
   ------------------------------------------------------------
   This file holds everything the tool knows. Editing it is safe:
   nothing here is program logic. See README.md for recipes.
   Bump DATA_VERSION whenever you change anything below.
   ============================================================ */
const DATA_VERSION = "2026-08-19";
/* ============================================================
   HAZARD CLASSES
   ============================================================ */
const G = {
  acid_ox:     {label:"Oxidizing acid",     store:"Acid cabinet, segregated from organics and organic acids; perchloric acid needs a dedicated washdown hood."},
  acid_min:    {label:"Mineral acid",       store:"Corrosives (acid) cabinet, below eye level, in secondary containment."},
  acid_org:    {label:"Organic acid",       store:"Corrosives cabinet, separated from oxidizing acids; many are also combustible."},
  base_strong: {label:"Caustic base",       store:"Corrosives (base) cabinet or a separate tray from acids."},
  base_org:    {label:"Amine / organic base", store:"Flammables cabinet if flammable; away from acids and oxidizers."},
  ox:          {label:"Oxidizer",           store:"Dedicated oxidizer cabinet or shelf, away from all combustibles and reducers."},
  red:         {label:"Reducing agent",     store:"Dry, away from oxidizers and acids."},
  water_react: {label:"Water-reactive",     store:"Dry, sealed, away from sinks, safety showers, and aqueous waste."},
  alkali_metal:{label:"Alkali / active metal", store:"Under mineral oil or inert gas, in a dry cabinet away from water and halogenated solvents."},
  pyro:        {label:"Pyrophoric",         store:"Inert atmosphere, dedicated storage, away from all combustibles and oxidizers."},
  flam_org:    {label:"Flammable organic",  store:"Flammables cabinet; quantity per fire code limits."},
  halo_solv:   {label:"Halogenated solvent", store:"Flammables or solvent cabinet; segregate from alkali metals and strong bases."},
  ether_perox: {label:"Peroxide former",    store:"Flammables cabinet, dated on receipt and opening, tested on schedule."},
  cyanide:     {label:"Cyanide salt",       store:"Locked, dry, well away from any acid and away from acid waste."},
  sulfide:     {label:"Sulfide salt",       store:"Dry, sealed, away from acids."},
  azide:       {label:"Azide",              store:"Away from acids and heavy metals; never down a metal drain line."},
  halogen:     {label:"Halogen",            store:"Ventilated corrosive storage, away from organics, metals, and ammonia."},
  ammonia:     {label:"Ammonia / ammonium", store:"Away from oxidizers, hypochlorite, and halogens; ventilated."},
  carbonate:   {label:"Carbonate / bicarbonate", store:"Ordinary shelf storage; keep out of acid waste containers, which it pressurizes."},
  metal_salt:  {label:"Heavy-metal salt",   store:"Dry, segregated, with heavy-metal waste stream identified."},
  shock:       {label:"Shock-sensitive",    store:"Kept wetted or as specified, dated, quantity-limited, on a tracked inventory."},
  gas_flam:    {label:"Flammable gas",      store:"Secured upright cylinder, 20 ft from oxidizing gases or behind a half-hour fire barrier."},
  gas_ox:      {label:"Oxidizing gas",      store:"Secured upright cylinder, 20 ft from flammable gases or behind a half-hour fire barrier."},
  gas_tox:     {label:"Toxic gas",          store:"Ventilated gas cabinet with monitoring as required."},
  gas_inert:   {label:"Inert gas",          store:"Secured upright cylinder; asphyxiation risk in confined space."},
  water:       {label:"Water / aqueous",    store:"—"},
  low:         {label:"No reactive class",  store:"Ordinary shelf storage. Segregation here is driven by toxicity, container, and housekeeping — not reactivity."}
};

/* ============================================================
   CHEMICAL LIST  ( n=name, s=synonyms, g=classes )
   ============================================================ */
const CHEMS = [
 {n:"Nitric acid", s:["HNO3"], g:["acid_ox","acid_min"]},
 {n:"Perchloric acid", s:["HClO4"], g:["acid_ox","acid_min","ox"]},
 {n:"Sulfuric acid (concentrated)", s:["H2SO4","oil of vitriol"], g:["acid_ox","acid_min"]},
 {n:"Chromic acid", s:["chromium trioxide","CrO3","chromerge"], g:["acid_ox","ox","metal_salt"]},
 {n:"Hydrochloric acid", s:["HCl","muriatic acid"], g:["acid_min"]},
 {n:"Hydrobromic acid", s:["HBr"], g:["acid_min"]},
 {n:"Hydrofluoric acid", s:["HF"], g:["acid_min"]},
 {n:"Phosphoric acid", s:["H3PO4"], g:["acid_min"]},
 {n:"Acetic acid (glacial)", s:["ethanoic acid"], g:["acid_org","flam_org"]},
 {n:"Formic acid", s:[], g:["acid_org"]},
 {n:"Trifluoroacetic acid", s:["TFA"], g:["acid_org","acid_min"]},
 {n:"Trichloroacetic acid", s:["TCA"], g:["acid_org"]},
 {n:"Citric acid", s:[], g:["acid_org"]},
 {n:"Picric acid", s:["2,4,6-trinitrophenol"], g:["shock","acid_org","ox"]},
 {n:"Acetic anhydride", s:[], g:["acid_org","water_react","flam_org"]},

 {n:"Sodium hydroxide", s:["NaOH","lye","caustic soda"], g:["base_strong"]},
 {n:"Potassium hydroxide", s:["KOH","caustic potash"], g:["base_strong"]},
 {n:"Ammonium hydroxide", s:["ammonia solution","aqueous ammonia","NH4OH"], g:["base_strong","ammonia"]},
 {n:"Calcium hydroxide", s:["slaked lime"], g:["base_strong"]},
 {n:"Triethylamine", s:["TEA"], g:["base_org","flam_org"]},
 {n:"Pyridine", s:[], g:["base_org","flam_org"]},
 {n:"Aniline", s:["aminobenzene"], g:["base_org","red"]},
 {n:"Ethylenediamine", s:["EDA"], g:["base_org","flam_org"]},
 {n:"Hydrazine", s:["N2H4"], g:["red","base_org","flam_org"]},

 {n:"Hydrogen peroxide", s:["H2O2"], g:["ox"]},
 {n:"Sodium hypochlorite (bleach)", s:["bleach","NaOCl","clorox"], g:["ox"]},
 {n:"Calcium hypochlorite", s:["HTH","pool chlorine"], g:["ox"]},
 {n:"Potassium permanganate", s:["KMnO4"], g:["ox","metal_salt"]},
 {n:"Potassium dichromate", s:["K2Cr2O7"], g:["ox","metal_salt"]},
 {n:"Sodium dichromate", s:[], g:["ox","metal_salt"]},
 {n:"Potassium chlorate", s:["KClO3"], g:["ox"]},
 {n:"Sodium chlorate", s:[], g:["ox"]},
 {n:"Potassium perchlorate", s:[], g:["ox"]},
 {n:"Ammonium persulfate", s:["APS"], g:["ox","ammonia"]},
 {n:"Sodium persulfate", s:[], g:["ox"]},
 {n:"Potassium nitrate", s:["saltpeter","KNO3"], g:["ox"]},
 {n:"Ammonium nitrate", s:["NH4NO3"], g:["ox","ammonia","shock"]},
 {n:"Silver nitrate", s:["AgNO3"], g:["ox","metal_salt"]},
 {n:"Benzoyl peroxide", s:["BPO"], g:["ox","shock"]},
 {n:"Peracetic acid", s:["peroxyacetic acid"], g:["ox","acid_org"]},
 {n:"Osmium tetroxide", s:["OsO4"], g:["ox","metal_salt"]},
 {n:"Iodine", s:["I2"], g:["ox","halogen"]},
 {n:"Bromine", s:["Br2"], g:["ox","halogen","acid_min"]},
 {n:"Chlorine", s:["Cl2"], g:["ox","halogen","gas_ox","gas_tox"]},
 {n:"Nitrous oxide", s:["N2O"], g:["gas_ox"]},
 {n:"Oxygen (cylinder)", s:["O2"], g:["gas_ox","ox"]},

 {n:"Sodium borohydride", s:["NaBH4"], g:["red","water_react"]},
 {n:"Lithium aluminum hydride", s:["LAH","LiAlH4"], g:["red","water_react","pyro"]},
 {n:"Calcium hydride", s:["CaH2"], g:["red","water_react"]},
 {n:"Sodium sulfite", s:[], g:["red"]},
 {n:"Sodium bisulfite", s:[], g:["red"]},
 {n:"Sodium thiosulfate", s:["hypo"], g:["red"]},
 {n:"Sodium metabisulfite", s:[], g:["red"]},
 {n:"Oxalic acid", s:[], g:["red","acid_org"]},
 {n:"Formaldehyde solution", s:["formalin"], g:["red","flam_org"]},
 {n:"Paraformaldehyde", s:["PFA"], g:["red","flam_org"]},
 {n:"Glutaraldehyde", s:[], g:["red"]},
 {n:"Dithiothreitol", s:["DTT"], g:["red","sulfide"]},
 {n:"2-Mercaptoethanol", s:["BME","beta-mercaptoethanol"], g:["red","sulfide","flam_org"]},

 {n:"Sodium metal", s:["Na"], g:["alkali_metal","water_react","red"]},
 {n:"Potassium metal", s:["K"], g:["alkali_metal","water_react","red"]},
 {n:"Lithium metal", s:["Li"], g:["alkali_metal","water_react","red"]},
 {n:"Magnesium (turnings/powder)", s:["Mg"], g:["alkali_metal","red"]},
 {n:"Aluminum powder", s:["Al"], g:["alkali_metal","red"]},
 {n:"Zinc powder", s:["Zn"], g:["alkali_metal","red"]},
 {n:"n-Butyllithium", s:["nBuLi","butyllithium"], g:["pyro","water_react","flam_org","red"]},
 {n:"tert-Butyllithium", s:["tBuLi"], g:["pyro","water_react","flam_org","red"]},
 {n:"Trimethylaluminum", s:["TMA"], g:["pyro","water_react"]},
 {n:"Raney nickel", s:[], g:["pyro","red","metal_salt"]},
 {n:"White phosphorus", s:["P4"], g:["pyro","water_react"]},
 {n:"Thionyl chloride", s:["SOCl2"], g:["water_react","acid_min"]},
 {n:"Acetyl chloride", s:[], g:["water_react","acid_min","flam_org"]},
 {n:"Phosphorus pentoxide", s:["P2O5"], g:["water_react"]},
 {n:"Calcium carbide", s:["CaC2"], g:["water_react"]},
 {n:"Trimethylsilyl chloride", s:["TMSCl"], g:["water_react","flam_org","acid_min"]},

 {n:"Acetone", s:[], g:["flam_org"]},
 {n:"Methanol", s:["methyl alcohol"], g:["flam_org"]},
 {n:"Ethanol", s:["ethyl alcohol","EtOH"], g:["flam_org"]},
 {n:"Isopropanol", s:["IPA","isopropyl alcohol","2-propanol"], g:["flam_org"]},
 {n:"n-Butanol", s:[], g:["flam_org"]},
 {n:"Glycerol", s:["glycerin"], g:["flam_org","red"]},
 {n:"Ethylene glycol", s:[], g:["flam_org"]},
 {n:"Hexane", s:["n-hexane"], g:["flam_org"]},
 {n:"Heptane", s:[], g:["flam_org"]},
 {n:"Pentane", s:[], g:["flam_org"]},
 {n:"Toluene", s:[], g:["flam_org"]},
 {n:"Xylene", s:[], g:["flam_org"]},
 {n:"Benzene", s:[], g:["flam_org"]},
 {n:"Ethyl acetate", s:[], g:["flam_org"]},
 {n:"Acetonitrile", s:["ACN","MeCN"], g:["flam_org"]},
 {n:"Dimethyl sulfoxide", s:["DMSO"], g:["flam_org","red"]},
 {n:"Dimethylformamide", s:["DMF"], g:["flam_org"]},
 {n:"Pyrogallol", s:[], g:["flam_org","red"]},
 {n:"Mineral oil", s:[], g:["flam_org"]},
 {n:"Paper / cellulose / sawdust", s:["cellulose","paper","wood","sawdust","kimwipes"], g:["flam_org"]},

 {n:"Diethyl ether", s:["ether","Et2O"], g:["ether_perox","flam_org"]},
 {n:"Tetrahydrofuran", s:["THF"], g:["ether_perox","flam_org"]},
 {n:"1,4-Dioxane", s:["dioxane"], g:["ether_perox","flam_org"]},
 {n:"Diisopropyl ether", s:["isopropyl ether","DIPE"], g:["ether_perox","flam_org"]},
 {n:"2-Methoxyethanol", s:[], g:["ether_perox","flam_org"]},
 {n:"Cyclohexene", s:[], g:["ether_perox","flam_org"]},

 {n:"Dichloromethane", s:["DCM","methylene chloride"], g:["halo_solv"]},
 {n:"Chloroform", s:["trichloromethane","CHCl3"], g:["halo_solv"]},
 {n:"Carbon tetrachloride", s:["CCl4"], g:["halo_solv"]},
 {n:"Trichloroethylene", s:["TCE"], g:["halo_solv"]},
 {n:"Chlorobenzene", s:[], g:["halo_solv","flam_org"]},
 {n:"Phenol-chloroform reagent", s:["TRIzol","phenol chloroform"], g:["halo_solv","acid_org"]},

 {n:"Sodium cyanide", s:["NaCN"], g:["cyanide"]},
 {n:"Potassium cyanide", s:["KCN"], g:["cyanide"]},
 {n:"Potassium ferricyanide", s:[], g:["cyanide","ox","metal_salt"]},
 {n:"Sodium sulfide", s:["Na2S"], g:["sulfide","base_strong"]},
 {n:"Sodium azide", s:["NaN3"], g:["azide"]},
 {n:"Hydrogen sulfide", s:["H2S"], g:["sulfide","gas_tox","gas_flam","red"]},

 {n:"Mercury (elemental)", s:["Hg"], g:["metal_salt"]},
 {n:"Mercuric chloride", s:[], g:["metal_salt","ox"]},
 {n:"Lead acetate", s:[], g:["metal_salt"]},
 {n:"Lead nitrate", s:[], g:["metal_salt","ox"]},
 {n:"Copper sulfate", s:["CuSO4"], g:["metal_salt"]},
 {n:"Copper metal / brass", s:["copper","brass","bronze"], g:["metal_salt"]},
 {n:"Silver salts", s:["silver"], g:["metal_salt"]},
 {n:"Cadmium chloride", s:[], g:["metal_salt"]},
 {n:"Ferric chloride", s:["iron(III) chloride"], g:["metal_salt","acid_min"]},

 {n:"Hydrogen (cylinder)", s:["H2"], g:["gas_flam","red"]},
 {n:"Acetylene", s:["C2H2"], g:["gas_flam"]},
 {n:"Methane / natural gas", s:["methane","CH4"], g:["gas_flam"]},
 {n:"Propane", s:[], g:["gas_flam"]},
 {n:"Ammonia (anhydrous)", s:["NH3 gas"], g:["ammonia","gas_flam","gas_tox","base_strong"]},
 {n:"Carbon monoxide", s:["CO"], g:["gas_flam","gas_tox","red"]},
 {n:"Nitrogen (cylinder)", s:["N2"], g:["gas_inert"]},
 {n:"Argon (cylinder)", s:["Ar"], g:["gas_inert"]},
 {n:"Carbon dioxide (cylinder)", s:["CO2","dry ice"], g:["gas_inert"]},

 {n:"Ammonium chloride", s:[], g:["ammonia"]},
 {n:"Ammonium sulfate", s:[], g:["ammonia"]},
 {n:"Water", s:["H2O","DI water","deionized water"], g:["water"]},
 {n:"Ethidium bromide", s:["EtBr"], g:["low"]},
 {n:"Agarose", s:[], g:["low"]},
 {n:"Sodium chloride", s:["NaCl","saline"], g:["low"]},
 {n:"Tris buffer", s:["Tris"], g:["base_org"]},
 {n:"Phosphate-buffered saline", s:["PBS"], g:["water"]},
 {n:"Magnesium chloride", s:["MgCl2"], g:["low"]},
 {n:"Calcium chloride", s:["CaCl2"], g:["low"]},
 {n:"Potassium chloride", s:["KCl"], g:["low"]},
 {n:"Magnesium sulfate", s:["MgSO4","Epsom salt"], g:["low"]},
 {n:"Sodium sulfate", s:["Na2SO4"], g:["low"]},
 {n:"Zinc chloride", s:["ZnCl2"], g:["metal_salt"]},
 {n:"Nickel chloride", s:["NiCl2"], g:["metal_salt"]},
 {n:"Cobalt chloride", s:["CoCl2"], g:["metal_salt"]},
 {n:"Barium chloride", s:["BaCl2"], g:["metal_salt"]},
 {n:"Ammonium molybdate", s:[], g:["metal_salt","ammonia"]},
 {n:"Potassium ferrocyanide", s:[], g:["cyanide","metal_salt"]},
 {n:"Sodium fluoride", s:["NaF"], g:["low"]},
 {n:"Sodium acetate", s:["NaOAc"], g:["low"]},
 {n:"Ammonium acetate", s:[], g:["ammonia"]},
 {n:"Ammonium bicarbonate", s:[], g:["ammonia","carbonate"]},
 {n:"Potassium carbonate", s:["K2CO3"], g:["carbonate","base_strong"]},
 {n:"Sodium phosphate", s:["Na2HPO4","monosodium phosphate"], g:["low"]},
 {n:"Potassium phosphate", s:["K2HPO4","KH2PO4"], g:["low"]},
 {n:"Boric acid", s:["H3BO3"], g:["low"]},
 {n:"Sodium borate", s:["borax"], g:["low"]},
 {n:"HEPES", s:[], g:["low"]},
 {n:"Glycine", s:[], g:["low"]},
 {n:"EDTA", s:["disodium EDTA","edetate"], g:["low"]},
 {n:"Sodium citrate", s:[], g:["low"]},
 {n:"Urea", s:[], g:["low"]},
 {n:"Guanidine hydrochloride", s:["GuHCl","guanidinium chloride"], g:["low"]},
 {n:"Guanidinium thiocyanate", s:["GITC","guanidine thiocyanate"], g:["cyanide"]},
 {n:"Sucrose", s:["table sugar"], g:["flam_org"]},
 {n:"Glucose", s:["dextrose"], g:["flam_org"]},
 {n:"Sodium dodecyl sulfate", s:["SDS","lauryl sulfate"], g:["flam_org"]},
 {n:"Triton X-100", s:[], g:["low"]},
 {n:"Tween 20", s:["polysorbate 20"], g:["low"]},
 {n:"Polyethylene glycol", s:["PEG"], g:["low"]},
 {n:"Formamide", s:[], g:["low"]},
 {n:"Diethyl pyrocarbonate", s:["DEPC"], g:["flam_org","water_react"]},
 {n:"Acrylamide", s:["bis-acrylamide","polyacrylamide"], g:["low"]},
 {n:"TEMED", s:["tetramethylethylenediamine"], g:["base_org","flam_org"]},
 {n:"IPTG", s:[], g:["low"]},
 {n:"Methylene blue", s:[], g:["low"]},
 {n:"Phenol", s:["carbolic acid"], g:["acid_org"]},
 {n:"Sodium nitrite", s:["NaNO2"], g:["ox"]},
 {n:"Potassium iodide", s:["KI"], g:["red"]},
 {n:"Sodium dithionite", s:["sodium hydrosulfite"], g:["red","water_react"]},
 {n:"Hydroxylamine", s:["NH2OH"], g:["red"]},
 {n:"Sodium hydride", s:["NaH"], g:["red","water_react"]},
 {n:"Potassium tert-butoxide", s:["KOtBu"], g:["base_strong","water_react","flam_org"]},
 {n:"Boron trifluoride etherate", s:["BF3 etherate"], g:["water_react","acid_min","flam_org"]},
 {n:"Sodium periodate", s:["NaIO4"], g:["ox"]},
 {n:"Potassium persulfate", s:[], g:["ox"]},
 {n:"Methyl ethyl ketone", s:["MEK","2-butanone"], g:["flam_org"]},
 {n:"Cyclohexane", s:[], g:["flam_org"]},
 {n:"Petroleum ether", s:["ligroin"], g:["flam_org"]},
 {n:"Diethylamine", s:[], g:["base_org","flam_org"]},
 {n:"Isoamyl alcohol", s:["3-methyl-1-butanol"], g:["flam_org"]},
 {n:"Isoflurane", s:[], g:["halo_solv"]},
 {n:"Liquid nitrogen", s:["LN2"], g:["gas_inert"]},
 {n:"Liquid helium", s:[], g:["gas_inert"]},
 {n:"Sodium bicarbonate", s:["baking soda","NaHCO3"], g:["carbonate"]},
 {n:"Sodium carbonate", s:["soda ash","Na2CO3"], g:["carbonate","base_strong"]}
];

/* ============================================================
   CLASS-PAIR RULES   sev: 3 = separate, 2 = caution, 1 = note
   ============================================================ */
const RULES = [
 {a:"ox",b:"flam_org",sev:3,p:"fire",t:"Oxidizer with combustible organic",
  w:"An oxidizer supplies its own oxygen. Contact with solvent, paper, or absorbent can ignite without an external source, and a spill onto shared secondary containment is enough."},
 {a:"ox",b:"ether_perox",sev:3,p:"fire",t:"Oxidizer with peroxide-forming solvent",
  w:"Same fire risk as any flammable, plus the ether's own peroxide burden."},
 {a:"ox",b:"red",sev:3,p:"runaway",t:"Oxidizer with reducing agent",
  w:"A complete redox pair. Reaction is exothermic and can accelerate on its own once started."},
 {a:"ox",b:"halo_solv",sev:2,p:"exotherm",t:"Oxidizer with halogenated solvent",
  w:"Less energetic than with a flammable, but strong oxidizers still attack halogenated solvents and can generate phosgene or other decomposition gases."},
 {a:"ox",b:"acid_min",sev:3,p:"toxic gas",t:"Oxidizer salt with acid",
  w:"Acid liberates the free oxidizing acid from hypochlorite, chlorate, or permanganate salts, giving chlorine, chlorine dioxide, or a strong oxidizer in solution."},
 {a:"ox",b:"acid_org",sev:3,p:"runaway",t:"Oxidizer with organic acid",
  w:"The acid is both a proton source and a fuel."},
 {a:"ox",b:"ammonia",sev:3,p:"NCl₃ / NH₂Cl",t:"Oxidizer with ammonia or ammonium salt",
  w:"Hypochlorite and ammonia give chloramines; concentrated conditions give nitrogen trichloride, which is explosive."},
 {a:"ox",b:"cyanide",sev:3,p:"toxic gas",t:"Oxidizer with cyanide",
  w:"Violent oxidation of cyanide with release of cyanogen or HCN."},
 {a:"ox",b:"sulfide",sev:3,p:"SO₂ / S",t:"Oxidizer with sulfide or thiol",
  w:"Rapid exothermic oxidation of sulfur; sulfur dioxide and elemental sulfur are typical products."},
 {a:"ox",b:"alkali_metal",sev:3,p:"ignition",t:"Oxidizer with active metal",
  w:"Metal powders and alkali metals ignite or detonate with solid oxidizers, especially on grinding or impact."},
 {a:"ox",b:"pyro",sev:3,p:"ignition",t:"Oxidizer with pyrophoric",
  w:"Immediate ignition. These never share a cabinet."},
 {a:"ox",b:"base_org",sev:2,p:"exotherm",t:"Oxidizer with amine",
  w:"Amines are oxidizable fuels; hypochlorite plus amine also gives chloramines."},
 {a:"ox",b:"metal_salt",sev:2,p:"catalytic decomposition",t:"Oxidizer with transition-metal salt",
  w:"Iron, copper, and manganese ions catalyze peroxide decomposition — pressure build-up in a closed container."},

 {a:"acid_ox",b:"flam_org",sev:3,p:"ignition / nitration",t:"Oxidizing acid with organic",
  w:"Nitric and perchloric acids attack organics directly. Perchloric acid plus alcohol or cellulose forms explosive perchlorate esters."},
 {a:"acid_ox",b:"ether_perox",sev:3,p:"explosion",t:"Oxidizing acid with ether",
  w:"Nitric or perchloric acid with an ether is a classic detonation pair."},
 {a:"acid_ox",b:"acid_org",sev:3,p:"explosion",t:"Oxidizing acid with organic acid",
  w:"Nitric acid with acetic acid or acetic anhydride is a well-documented explosive combination."},
 {a:"acid_ox",b:"red",sev:3,p:"runaway",t:"Oxidizing acid with reducing agent",
  w:"Vigorous redox with heat and gas evolution."},
 {a:"acid_ox",b:"halo_solv",sev:2,p:"exotherm",t:"Oxidizing acid with halogenated solvent",
  w:"Concentrated nitric or sulfuric acid reacts with chlorinated solvents; keep waste streams separate."},
 {a:"acid_ox",b:"acid_min",sev:2,p:"Cl₂ / NOCl",t:"Oxidizing acid with mineral acid",
  w:"Nitric plus hydrochloric gives aqua regia — nitrosyl chloride and chlorine, and it pressurizes closed containers."},
 {a:"acid_ox",b:"base_strong",sev:3,p:"violent exotherm",t:"Concentrated acid with caustic",
  w:"Neutralization heat is enough to boil and spatter both."},
 {a:"acid_ox",b:"base_org",sev:3,p:"violent exotherm",t:"Oxidizing acid with amine",
  w:"Exothermic neutralization plus oxidation of the amine."},
 {a:"acid_ox",b:"metal_salt",sev:2,p:"NOx",t:"Oxidizing acid with metal or metal salt",
  w:"Nitric acid dissolves most metals with nitrogen oxide evolution."},

 {a:"acid_min",b:"base_strong",sev:3,p:"violent exotherm",t:"Acid with caustic",
  w:"Neutralization releases enough heat to spatter concentrated material. Separate cabinets, or at minimum separate secondary containment."},
 {a:"acid_min",b:"cyanide",sev:3,p:"HCN",t:"Acid with cyanide",
  w:"Any acid liberates hydrogen cyanide from cyanide salts. This is the pairing that kills people in labs."},
 {a:"acid_min",b:"sulfide",sev:3,p:"H₂S",t:"Acid with sulfide",
  w:"Hydrogen sulfide is generated immediately; it deadens the sense of smell before it reaches lethal concentration."},
 {a:"acid_min",b:"azide",sev:3,p:"HN₃",t:"Acid with azide",
  w:"Hydrazoic acid is volatile, toxic, and explosive."},
 {a:"acid_min",b:"alkali_metal",sev:3,p:"H₂",t:"Acid with active metal",
  w:"Hydrogen evolution with heat — the mixture ignites itself in a closed space."},
 {a:"acid_min",b:"water_react",sev:3,p:"HCl / exotherm",t:"Aqueous acid with water-reactive material",
  w:"The water content alone drives a violent reaction."},
 {a:"acid_min",b:"base_org",sev:2,p:"exotherm",t:"Acid with amine",
  w:"Exothermic salt formation; contain and separate."},
 {a:"acid_min",b:"acid_org",sev:1,p:"—",t:"Mineral acid with organic acid",
  w:"Generally storable together in a corrosives cabinet, but keep organic acids away from oxidizing acids and treat them as combustible."},

 {a:"acid_org",b:"base_strong",sev:2,p:"exotherm",t:"Organic acid with caustic",
  w:"Neutralization exotherm; glacial acetic acid is also flammable."},

 {a:"base_strong",b:"halo_solv",sev:3,p:"carbene / exotherm",t:"Strong base with halogenated solvent",
  w:"Dichloromethane or chloroform with a strong base runs away exothermically and generates dichlorocarbene; chloroform plus acetone plus base is a documented explosion."},
 {a:"base_strong",b:"alkali_metal",sev:2,p:"H₂",t:"Caustic with amphoteric metal",
  w:"Aluminum and zinc dissolve in caustic with hydrogen evolution."},
 {a:"base_strong",b:"water_react",sev:3,p:"exotherm",t:"Aqueous caustic with water-reactive material",
  w:"Water content drives the reaction regardless of pH."},
 {a:"base_strong",b:"metal_salt",sev:1,p:"precipitate",t:"Caustic with metal salt",
  w:"Metal hydroxide precipitation; relevant mostly for waste-stream planning."},

 {a:"alkali_metal",b:"halo_solv",sev:3,p:"detonation",t:"Alkali metal with halogenated solvent",
  w:"Sodium or potassium with carbon tetrachloride, chloroform, or dichloromethane is shock-sensitive and has caused fatalities. Never quench alkali metals in halogenated solvent."},
 {a:"alkali_metal",b:"water",sev:3,p:"H₂ + fire",t:"Active metal with water",
  w:"Hydrogen evolution with enough heat to ignite it."},
 {a:"alkali_metal",b:"acid_org",sev:3,p:"H₂",t:"Active metal with organic acid",
  w:"Hydrogen evolution; alcohols and acids both attack alkali metals."},

 {a:"water_react",b:"water",sev:3,p:"exotherm / gas",t:"Water-reactive material with water",
  w:"Includes ambient humidity, wet glassware, and shared containment with aqueous waste."},
 {a:"water_react",b:"flam_org",sev:1,p:"—",t:"Water-reactive with flammable",
  w:"Compatible in principle, but confirm the solvent is dry — trace water is the failure mode."},

 {a:"pyro",b:"water",sev:3,p:"ignition",t:"Pyrophoric with water",
  w:"Immediate ignition on contact with water or moist air."},
 {a:"pyro",b:"flam_org",sev:2,p:"fire load",t:"Pyrophoric with flammable",
  w:"If the pyrophoric ignites, a co-located flammable turns it into a room fire. Store the pyrophoric on its own."},
 {a:"pyro",b:"halo_solv",sev:3,p:"violent reaction",t:"Pyrophoric with halogenated solvent",
  w:"Organolithiums and metal alkyls react violently with halogenated solvents."},

 {a:"halogen",b:"flam_org",sev:3,p:"ignition",t:"Halogen with organic",
  w:"Halogenation is exothermic and can ignite the organic."},
 {a:"halogen",b:"ammonia",sev:3,p:"NCl₃ / NI₃",t:"Halogen with ammonia",
  w:"Nitrogen trihalides are contact-explosive."},
 {a:"halogen",b:"red",sev:3,p:"runaway",t:"Halogen with reducing agent",
  w:"Direct redox pair."},
 {a:"halogen",b:"alkali_metal",sev:3,p:"ignition",t:"Halogen with active metal",
  w:"Direct combination, often violent."},

 {a:"azide",b:"metal_salt",sev:3,p:"metal azide",t:"Azide with heavy metal",
  w:"Lead, copper, and silver azides are primary explosives sensitive to friction. This is why azide solutions never go down a metal drain line."},
 {a:"azide",b:"halo_solv",sev:3,p:"diazidomethane",t:"Azide with halogenated solvent",
  w:"Sodium azide with dichloromethane forms diazidomethane, which detonates unpredictably. It shows up in waste containers more often than in reactions."},
 {a:"azide",b:"ox",sev:3,p:"explosion",t:"Azide with oxidizer",
  w:"Energetic and unpredictable."},

 {a:"cyanide",b:"water",sev:2,p:"HCN",t:"Cyanide with water",
  w:"Cyanide salts hydrolyze in moist air to release HCN. Keep dry and sealed."},

 {a:"shock",b:"metal_salt",sev:3,p:"metal picrate",t:"Shock-sensitive material with metal",
  w:"Picric acid forms picrate salts with metal caps, spatulas, and shelving — friction-sensitive."},
 {a:"shock",b:"acid_min",sev:3,p:"sensitization",t:"Shock-sensitive material with acid",
  w:"Acid contact can sensitize or destabilize the material further."},
 {a:"shock",b:"ox",sev:3,p:"detonation",t:"Shock-sensitive material with oxidizer",
  w:"Do not co-locate under any quantity."},

 {a:"gas_flam",b:"gas_ox",sev:3,p:"fire",t:"Flammable gas cylinder with oxidizing gas cylinder",
  w:"Standard segregation is 20 ft, or a non-combustible barrier at least 5 ft high with a half-hour fire rating."},
 {a:"gas_flam",b:"ox",sev:3,p:"fire",t:"Flammable gas with oxidizer",
  w:"Keep cylinders away from solid and liquid oxidizers as well as oxidizing gases."},
 {a:"gas_ox",b:"flam_org",sev:3,p:"fire",t:"Oxidizing gas with combustible",
  w:"Oxygen enrichment lowers the ignition energy of everything nearby, including cabinet materials and regulator grease."},

 {a:"ether_perox",b:"acid_min",sev:2,p:"peroxide formation",t:"Peroxide former with acid",
  w:"Acid accelerates peroxide formation and can trigger violent decomposition of accumulated peroxide."},

 {a:"carbonate",b:"acid_min",sev:2,p:"CO₂ pressure",t:"Carbonate with acid",
  w:"Rapid CO₂ evolution. In a capped waste jug or a closed spill tray this ruptures the container — one of the most common non-reactive failures in a lab."},
 {a:"carbonate",b:"acid_ox",sev:2,p:"CO₂ pressure",t:"Carbonate with oxidizing acid",
  w:"Gas evolution plus the oxidizing acid's own hazards; vent and add slowly if neutralizing deliberately."},
 {a:"carbonate",b:"acid_org",sev:2,p:"CO₂ pressure",t:"Carbonate with organic acid",
  w:"Effervescence is mild at the bench and dangerous in a sealed container."},
 {a:"metal_salt",b:"red",sev:1,p:"—",t:"Metal salt with reducing agent",
  w:"Reduction to free metal; usually a waste-characterization issue rather than a storage hazard."}
];

/* ============================================================
   NAMED PAIR OVERRIDES — specific, well-documented combinations
   ============================================================ */
const PAIRS = [
 {a:"Sodium hypochlorite (bleach)",b:"Ammonium hydroxide",sev:3,p:"chloramine gas",t:"Bleach with ammonia",
  w:"Monochloramine and dichloramine off-gas immediately; in a closed cabinet the vapors alone are enough."},
 {a:"Sodium hypochlorite (bleach)",b:"Hydrochloric acid",sev:3,p:"Cl₂",t:"Bleach with acid",
  w:"Chlorine gas released at once. Applies to any acid, including acetic acid in a shared spill tray."},
 {a:"Hydrogen peroxide",b:"Acetone",sev:3,p:"acetone peroxide",t:"Peroxide with ketone",
  w:"Under acidic conditions this forms triacetone triperoxide, a primary explosive. It has been produced accidentally in waste containers."},
 {a:"Nitric acid",b:"Acetic anhydride",sev:3,p:"detonation",t:"Nitric acid with acetic anhydride",
  w:"Forms acetyl nitrate. Documented laboratory detonations."},
 {a:"Nitric acid",b:"Ethanol",sev:3,p:"ethyl nitrate",t:"Nitric acid with alcohol",
  w:"Nitrate ester formation with a violent exotherm."},
 {a:"Perchloric acid",b:"Paper / cellulose / sawdust",sev:3,p:"perchlorate ester",t:"Perchloric acid with cellulose",
  w:"Cellulose perchlorate is friction-sensitive. Never use paper towels or wooden shelving with perchloric acid."},
 {a:"Sodium azide",b:"Copper metal / brass",sev:3,p:"copper azide",t:"Azide with copper plumbing",
  w:"Copper azide accumulates in drain traps and detonates on plumbing work."},
 {a:"Sodium azide",b:"Lead acetate",sev:3,p:"lead azide",t:"Azide with lead",
  w:"Lead azide is a primary explosive."},
 {a:"Sodium azide",b:"Dichloromethane",sev:3,p:"diazidomethane",t:"Azide with dichloromethane",
  w:"Forms diazidomethane, which detonates without warning. Common in mixed halogenated waste."},
 {a:"Potassium permanganate",b:"Glycerol",sev:3,p:"ignition",t:"Permanganate with glycerol",
  w:"Ignites spontaneously after a short induction period."},
 {a:"Chloroform",b:"Acetone",sev:2,p:"exotherm",t:"Chloroform with acetone",
  w:"Safe alone, but with a trace of base the condensation runs away. Documented laboratory explosion."},
 {a:"Silver nitrate",b:"Ammonium hydroxide",sev:3,p:"silver nitride",t:"Silver nitrate with ammonia",
  w:"Tollens' reagent left standing deposits silver nitride, which is contact-explosive. Never store the mixture."},
 {a:"Mercury (elemental)",b:"Aluminum powder",sev:3,p:"amalgam",t:"Mercury with aluminum",
  w:"Amalgamation destroys aluminum structures and defeats the oxide layer."},
 {a:"Hydrogen peroxide",b:"Copper sulfate",sev:2,p:"O₂ pressure",t:"Peroxide with copper salt",
  w:"Catalytic decomposition pressurizes closed containers — a common cause of ruptured waste jugs."},
 {a:"Picric acid",b:"Copper metal / brass",sev:3,p:"copper picrate",t:"Picric acid with metal",
  w:"Metal picrates form on caps, spatulas, and shelf brackets and are friction-sensitive."},
 {a:"Hydrofluoric acid",b:"Calcium hydroxide",sev:1,p:"CaF₂",t:"HF with calcium",
  w:"This is the intended neutralization pathway, not an incompatibility — but store the calcium gluconate or hydroxide outside the acid cabinet so it stays reachable during a spill."},
 {a:"Sodium metal",b:"Carbon tetrachloride",sev:3,p:"detonation",t:"Sodium with carbon tetrachloride",
  w:"Shock-sensitive mixture. Never use halogenated solvent on an alkali metal fire either."},
 {a:"Calcium hypochlorite",b:"Ethanol",sev:3,p:"ignition",t:"Hypochlorite solid with alcohol",
  w:"Solid hypochlorite ignites alcohols on contact."},
 {a:"Guanidinium thiocyanate",b:"Sodium hypochlorite (bleach)",sev:3,p:"HCN / cyanogen chloride",t:"Thiocyanate lysis buffer with bleach",
  w:"Bleaching TRIzol or GITC lysate to decontaminate it releases cyanide gas. This kills people who are trying to be careful — never bleach guanidinium waste."},
 {a:"Urea",b:"Sodium hypochlorite (bleach)",sev:3,p:"NCl₃",t:"Urea with bleach",
  w:"Nitrogen trichloride, which is contact-explosive and a severe respiratory irritant."},
 {a:"Sodium nitrite",b:"Diethylamine",sev:3,p:"nitrosamine",t:"Nitrite with secondary amine",
  w:"Forms N-nitrosamines, which are potent carcinogens. Applies to any secondary amine under acidic conditions."},
 {a:"Ammonium persulfate",b:"TEMED",sev:2,cap:2,p:"polymerization",t:"APS with TEMED — the intended pair",
  w:"This is the gel polymerization reaction, not an accident. Still store the dry persulfate away from the TEMED bottle and other organics: as a solid it is an oxidizer."},
 {a:"Dimethyl sulfoxide",b:"Thionyl chloride",sev:3,p:"runaway",t:"DMSO with acyl or sulfonyl chloride",
  w:"DMSO decomposes exothermically with acid chlorides and strong acids; documented as a violent runaway on scale."}
];

/* ============================================================
   SELF-FLAGS — standing notes on a single material
   ============================================================ */
const SELF = {
  ether_perox:{t:"Peroxide former present",w:"Date on receipt and on opening, test before distillation or evaporation, and dispose on schedule rather than by inventory need."},
  shock:{t:"Shock-sensitive material present",w:"Check hydration state, quantity, cap condition, and the tracked-inventory entry. Do not move a dried container."},
  pyro:{t:"Pyrophoric present",w:"Confirm inert-atmosphere technique, buddy system, and a Class D extinguisher or dry sand — not water or CO₂."},
  cyanide:{t:"Cyanide present",w:"Confirm locked storage, a cyanide-free acid waste stream, and that the antidote and response plan are documented."}
};
